- name: Set mariadb container
  community.docker.docker_container:
    state: "{{ 'absent' if all__inception__stop else 'started' }}"
    name: "inception-mariadb-1"
    image: "inception_mariadb"
    env_file: "{{ all__inception__src_dir }}/.env"
    restart_policy: always
    networks:
      - name: "inception"
        aliases: mariadb
    volumes:
      - "inception_db:/var/lib/mysql"

- name: Set php container
  community.docker.docker_container:
    state: "{{ 'absent' if all__inception__stop else 'started' }}"
    name: "inception-php-1"
    image: "inception_php"
    env_file: "{{ all__inception__src_dir }}/.env"
    restart_policy: always
    networks:
      - name: "inception"
        aliases: php
    volumes:
      - "inception_wp-data:/var/www/html"

- name: Set nginx container
  community.docker.docker_container:
    state: "{{ 'absent' if all__inception__stop else 'started' }}"
    name: "inception-nginx-1"
    image: "inception_nginx"
    env_file: "{{ all__inception__src_dir }}/.env"
    restart_policy: always
    ports:
      - 443:443
    networks:
      - name: "inception"
        aliases: nginx
    volumes:
      - "inception_wp-data:/var/www/html"
