- name: Shutdown inception and prune system
  hosts: cloud1
  tasks:
    - name: Remove nginx container
      docker_container:
        name: inception-nginx-1
        state: absent
    
    - name: Remove php container
      docker_container:
        name: inception-php-1
        state: absent
    
    - name: Remove mariadb container
      docker_container:
        name: inception-mariadb-1
        state: absent

    - name: Remove inception network
      docker_network:
        state: absent
        name: inception

    - name: Remove nginx image
      docker_image:
        state: absent
        name: inception_nginx
    
    - name: Remove php image
      docker_image:
        state: absent
        name: inception_php

    - name: Remove mariadb image
      docker_image:
        state: absent
        name: inception_mariadb 
    
    - name: Remove wp-data volume
      docker_volume:
        state: absent
        name: inception_wp-data

    - name: Remove db volume
      docker_volume:
        state: absent
        name: inception_db

    - name: Remove inception folder
      file:
        path: "{{ ansible_user_dir }}/inception"
        state: absent

    - name: Remove volume folder
      become: true
      file:
        path: "{{ ansible_user_dir }}/data"
        state: absent
