- name: Remove required packages and docker on hosts
  become: true
  hosts: cloud1
  vars:
    deb_architecture: {
      "aarch64": "arm64",
      "x86_64": "amd64"
    }
  tasks:
    - name: Remove docker packages
      apt:
        pkg:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: absent

    - name: Print architecture variables
      debug:
        msg: "Architecture: {{ deb_architecture[ansible_architecture] | default(ansible_architecture) }}, Codename: {{ ansible_lsb.codename }}"

    - name: Remove Docker repository
      apt_repository:
        repo: >-
          deb [arch={{ deb_architecture[ansible_architecture] | default(ansible_architecture) }}
          signed-by=/etc/apt/keyrings/docker.gpg]
          https://download.docker.com/linux/debian {{ ansible_lsb.codename }} stable
        filename: docker
        state: absent

    - name: Remove Docker's official GPG key
      apt_key:
        url: https://download.docker.com/linux/debian/gpg
        keyring: /etc/apt/keyrings/docker.gpg
        state: absent

    - name: Remove system packages
      apt:
        pkg:
          - vim
          - curl
          - wget
          - git
          - net-tools
          - apt-transport-https
          - gnupg
          - software-properties-common
        state: absent
        update_cache: true
